### ISSUE TITLE
Blog: Required Functionality and Issue tracker

### ISSUE THREAD

**Issue by salman-bhai** [IEEE-NITK/ieee-nitk.github.io#1]
- [x] Make the blog background match the blue hue of the front page of the site.
- [x] Add Facebook comments plugin.
- [x] Add Google Analytics to view people viewing the blog.
- [x] Remove Disqus and disable it properly!
- [x] Add Pagination to the current Scheme of things!
- [x] Add Gyan section according how @adithyabhatkajake suggested it!
- [x] Add HTTPS support
- [x] Separate articles according to each SIG using post.categories.
- [x] Change favicon to png instead of current jpg with white background.
- [x] Add themes for each of the blogs as suggested by @adithyabhatkajake 
- [x] Add Travis CI Support for the blog to run automated checks!

**Comment by salman-bhai** [comment]
Issue opened in the other repository!

**Comment by salman-bhai** [comment]
@viggi-v can you change the blog background?

**Comment by salman-bhai** [comment]
@viggi-v Can you change the background

**Comment by salman-bhai** [comment]
@viggi-v I updated the list of stuff to be done!

**Comment by salman-bhai** [comment]
@viggi-v what happened to the Post by SIG using post.categories?

**Comment by salman-bhai** [comment]
@hehaichi is assigned to integrate Travis-CL

**Comment by adithyabhatkajake** [comment]
We should have seperate issues for every enhancement/change/problem. It will be hard to trace later.

**Comment by salman-bhai** [comment]
Can you create what all tags should be there? I'll make the Issues based on the new tags created!

**Comment by salman-bhai** [comment]
@viggi-v any updates?

**Comment by salman-bhai** [comment]
@viggi-v any updates about the post.cateogries Issue?
