### ISSUE TITLE
Migrate static assets to a new repo for centralized management

### ISSUE THREAD

**Issue by nishant-nayak** [IEEE-NITK/ieee-nitk.github.io#315]
Moving static assets like Society logos, Branch logos and other images ensures consistency across all website repositories ([blog](https://github.com/IEEE-NITK/blog), [gyan](https://github.com/IEEE-NITK/gyan) and [virtual-expo](https://github.com/IEEE-NITK/virtual-expo)). 

## Tasks

- [ ] Identify common assets across all 4 website repositories
- [ ] Move the assets to a new repository
- [ ] Update the asset links on all 4 repositories to fetch assets from the new repository

**Comment by nishant-nayak** [comment]
Common assets repository: [https://github.com/IEEE-NITK/website-assets](https://github.com/IEEE-NITK/website-assets)
