### ISSUE TITLE
Design changes - Mystify

### ISSUE THREAD

**Issue by Shashankhs17** [IEEE-NITK/ieee-nitk.github.io#371]
The related files are present in the [mystify ](https://github.com/IEEE-NITK/ieee-nitk.github.io/tree/mystify) branch of this repo ([mystify.html](https://github.com/IEEE-NITK/ieee-nitk.github.io/blob/mystify/mystify.html)  and [/mystify](https://github.com/IEEE-NITK/ieee-nitk.github.io/tree/mystify/mystify)). Clone the repo and checkout to the mystify branch. The changes should be pushed to a new branch and a pull request to mystify branch should be created.

## Tasks

- [x] Change the fonts of the website (Headings as well as paragraphs), to make it more appealing. [Google fonts](https://fonts.google.com/) is one of the useful resources.
- [ ] Add a new style to the registration button. Add hover effects and responsive behavior as well.
- [ ] Change the color palette of texts (Optional, do it only if the new color palette looks better than the current one).
