### ISSUE TITLE
Main Website: Required Functionality and Issue Tracker

### ISSUE THREAD

**Issue by salman-bhai** [IEEE-NITK/ieee-nitk.github.io#48]
- [x] Update Team Page on the Main Website as to put current Executive members and probably have a separate page/section for Alumni.
- [x] Update events section in the Main Website with photos of the events as well if possible!
- [x] Add Google Analytics to view Page and allow for number of people viewing it!

What do you think about @viggi-v @adithyabhatkajake?

**Comment by adithyabhatkajake** [comment]
Not an issue. We can work on this.

**Comment by salman-bhai** [comment]
Cool, I've contacted the core. Should get it around the weekend!

**Comment by salman-bhai** [comment]
@viggi-v should we assign this to any junior?

**Comment by salman-bhai** [comment]
@viggi-v should we asssign this to a junior?

**Comment by salman-bhai** [comment]
@viggi-v any updates?

**Comment by salman-bhai** [comment]
@viggi-v ?
